default: &default
  adapter: postgresql
  encoding: unicode
  username: ruby
  password: ruby
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api-capptan_development

test:
  <<: *default
  database: api-capptan_test

production:
  <<: *default
  database: api-capptan_production
  username: api-capptan
  password: <%= ENV['API-CAPPTAN_DATABASE_PASSWORD'] %>
